Repository OFP-CDA-Mulhouse-2020/parisportif1, pull requests merged in 2020-12, with the labels that each got.

#60 fix property name
  code/src/Entity/User.php
  code/tests/Entity/UserTest.php
Labels: bug

#66 Feature/login form
  code/config/packages/framework.yaml
  code/config/packages/security.yaml
  code/migrations/Version20201203143834.php
  code/public/.htaccess
  code/src/Controller/ProfileController.php
  code/src/Controller/SecurityController.php
  code/src/DataFixtures/UserFixtures.php
  code/src/Entity/User.php
  code/src/Form/LoginFormType.php
  code/src/Repository/UserRepository.php
  code/src/Security/LoginAuthenticator.php
  code/symfony.lock
  code/templates/profile/index.html.twig
  code/templates/security/login.html.twig
  code/tests/Functional/LoginFormTest.php
Labels: enhancement

#67 Feature/login form
  code/src/Controller/ProfileController.php
  code/src/Controller/SecurityController.php
  code/src/Entity/User.php
  code/src/Form/LoginFormType.php
  code/src/Repository/UserRepository.php
  code/src/Security/LoginAuthenticator.php
  code/tests/Entity/UserTest.php
  code/tests/Functional/LoginFormTest.php
Labels: enhancement

#68 Merge registration form feature
  code/.phpunit-watcher.yml
  code/config/packages/framework.yaml
  code/migrations/Version20201204123915.php
  code/migrations/Version20201207121155.php
  code/phpunit.xml.dist
  code/src/Controller/RegisterController.php
  code/src/DataFixtures/UserFixtures.php
  code/src/Entity/User.php
  code/src/Form/RegisterFormType.php
  code/src/Repository/UserRepository.php
  code/templates/base.html.twig
  code/templates/register/index.html.twig
  code/tests/Entity/UserTest.php
  code/tests/Functional/RegisterFormTest.php
  docker-compose.yaml
Labels: enhancement

#74 Readme update for milestone 4
  README.md
Labels: documentation

#75 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#84 Feature/payment
  code/src/Entity/Payment.php
  code/src/Repository/PaymentRepository.php
  code/tests/Entity/PaymentTest.php
  docs/diagrams/src/CDA Bet.wsd
Labels: enhancement

#78 Feature/geo entity
  code/src/Entity/Country.php
  code/src/Entity/Event.php
  code/src/Entity/Status.php
  code/src/Entity/TimeZone.php
  code/src/Repository/CountryRepository.php
  code/src/Repository/EventRepository.php
  code/src/Repository/StatusRepository.php
  code/src/Repository/TimeZoneRepository.php
  code/tests/Entity/CountryTest.php
  code/tests/Entity/EventTest.php
  code/tests/Entity/StatusTest.php
  code/tests/Entity/TimeZoneTest.php
Labels: enhancement

#82 Feature/sport entity
  code/src/Entity/Sport.php
  code/src/Entity/SportType.php
  code/src/Repository/SportRepository.php
  code/src/Repository/SportTypeRepository.php
  code/tests/Entity/SportTest.php
  code/tests/Entity/SportTypeTest.php
Labels: enhancement

#87 Feature/wallet
  code/src/Entity/Wallet.php
  code/src/Repository/WalletRepository.php
  code/tests/Entity/WalletTest.php
Labels: enhancement

#85 Feature/odds
  code/src/Entity/Odds.php
  code/src/Repository/OddsRepository.php
  code/tests/Entity/OddsTest.php
  docs/diagrams/src/CDA Bet.wsd
Labels: enhancement

#89 Feature/bet
  code/src/Entity/Bet.php
  code/src/Repository/BetRepository.php
  code/tests/Entity/BetTest.php
Labels: enhancement
